version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: localsqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@sa12345"
      TZ: "America/Sao_Paulo"
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql-2019
      
volumes:
  my-volume:
